use crate::compiler::pattern::compile_match_with_patterns;
use crate::errors::compile::CompileError;
use crate::ir::nodes::{IrApi, IrDecl, IrExpr, IrFunction, IrProgram};

/// Compile an IR program to JavaScript
pub fn compile_ir_to_js(ir: &IrProgram) -> Result<String, CompileError> {
    let mut output = String::new();

    // Add header comment
    output.push_str("// Generated by MTPScript Compiler\n");
    output.push_str("// Deterministic JavaScript subset - no eval, class, this, try/catch, loops, or global mutation\n\n");

    for decl in &ir.decls {
        match decl {
            IrDecl::Function(func) => {
                let func_js = compile_function(func)?;
                output.push_str(&func_js);
                output.push_str("\n\n");
            }
            IrDecl::Api(api) => {
                let api_js = compile_api(api)?;
                output.push_str(&api_js);
                output.push_str("\n\n");
            }
        }
    }

    Ok(output)
}

/// Compile a function to JavaScript
fn compile_function(func: &IrFunction) -> Result<String, CompileError> {
    let mut output = String::new();

    // Function signature
    output.push_str("function ");
    output.push_str(&func.name);
    output.push('(');

    // Parameters
    let param_names: Vec<String> = func.params.iter().map(|(name, _)| name.clone()).collect();
    output.push_str(&param_names.join(", "));
    output.push_str(") {\n");

    // Function body - MTPScript functions implicitly return their body expression
    output.push_str("  return ");
    let body_js = compile_expr(&func.body, 1)?;
    output.push_str(&body_js);
    output.push_str(";\n");

    output.push('}');

    Ok(output)
}

/// Compile an API to JavaScript
fn compile_api(api: &IrApi) -> Result<String, CompileError> {
    let mut output = String::new();

    // API handler function
    output.push_str("function ");
    output.push_str(&api_method_to_handler_name(&api.method));
    output.push_str("_");
    output.push_str(&api.path.replace("/", "_").replace("{", "").replace("}", ""));
    output.push_str("() {\n");

    // API body
    let body_js = compile_expr(&api.body, 1)?;
    output.push_str(&body_js);
    output.push('\n');

    output.push('}');

    Ok(output)
}

/// Convert HTTP method to handler function name
fn api_method_to_handler_name(method: &crate::parser::ast::HttpMethod) -> &'static str {
    match method {
        crate::parser::ast::HttpMethod::Get => "handle_get",
        crate::parser::ast::HttpMethod::Post => "handle_post",
        crate::parser::ast::HttpMethod::Put => "handle_put",
        crate::parser::ast::HttpMethod::Delete => "handle_delete",
        crate::parser::ast::HttpMethod::Patch => "handle_patch",
    }
}

/// Compile an expression to JavaScript with proper indentation
fn compile_expr(expr: &IrExpr, indent: usize) -> Result<String, CompileError> {
    let indent_str = "  ".repeat(indent);

    match expr {
        IrExpr::String(s, _) => Ok(format!("\"{}\"", s)),
        IrExpr::Number(n, _) => Ok(n.to_string()),
        IrExpr::Decimal(d, _) => Ok(format!("\"{}\"", d)),
        IrExpr::Boolean(b, _) => Ok(b.to_string()),

        IrExpr::Array(elements, _) => {
            let elements_js: Result<Vec<String>, _> =
                elements.iter().map(|e| compile_expr(e, 0)).collect();
            let elements_js = elements_js?;
            Ok(format!("[{}]", elements_js.join(", ")))
        }

        IrExpr::Object(fields, _) => {
            let fields_js: Result<Vec<String>, _> = fields
                .iter()
                .map(|(k, v)| {
                    let v_js = compile_expr(v, 0)?;
                    Ok(format!("\"{}\": {}", k, v_js))
                })
                .collect();
            let fields_js = fields_js?;
            Ok(format!("{{{}}}", fields_js.join(", ")))
        }

        IrExpr::Var(name, _) => Ok(name.clone()),

        IrExpr::Dot(expr, field, _) => {
            let expr_js = compile_expr(expr, 0)?;
            Ok(format!("{}.{}", expr_js, field))
        }

        IrExpr::Index(array, index, _) => {
            let array_js = compile_expr(array, 0)?;
            let index_js = compile_expr(index, 0)?;
            Ok(format!("{}[{}]", array_js, index_js))
        }

        IrExpr::Call { func, args, .. } => {
            let func_js = compile_expr(func, 0)?;
            let args_js: Result<Vec<String>, _> = args.iter().map(|a| compile_expr(a, 0)).collect();
            let args_js = args_js?;
            Ok(format!("{}({})", func_js, args_js.join(", ")))
        }

        IrExpr::TailCall { func, args, .. } => {
            // Tail calls are compiled as regular calls since we don't have TCO in JS
            let func_js = compile_expr(func, 0)?;
            let args_js: Result<Vec<String>, _> = args.iter().map(|a| compile_expr(a, 0)).collect();
            let args_js = args_js?;
            Ok(format!("{}({})", func_js, args_js.join(", ")))
        }

        IrExpr::Unary(op, expr, _) => {
            let expr_js = compile_expr(expr, 0)?;
            let op_js = match op {
                crate::parser::ast::BinOp::Add => "+",
                crate::parser::ast::BinOp::Sub => "-",
                crate::parser::ast::BinOp::Mul => "*", // Not really unary, but handle anyway
                crate::parser::ast::BinOp::Div => "/", // Not really unary, but handle anyway
                _ => {
                    return Err(CompileError::CodeGenError(format!(
                        "Unsupported unary operator: {:?}",
                        op
                    )))
                }
            };
            Ok(format!("{}{}", op_js, expr_js))
        }

        IrExpr::Binary(op, left, right, _) => {
            let left_js = compile_expr(left, 0)?;
            let right_js = compile_expr(right, 0)?;
            let op_js = match op {
                crate::parser::ast::BinOp::Add => "+",
                crate::parser::ast::BinOp::Sub => "-",
                crate::parser::ast::BinOp::Mul => "*",
                crate::parser::ast::BinOp::Div => "/",
                crate::parser::ast::BinOp::Eq => "===",
                crate::parser::ast::BinOp::Ne => "!==",
                crate::parser::ast::BinOp::Lt => "<",
                crate::parser::ast::BinOp::Gt => ">",
                crate::parser::ast::BinOp::Le => "<=",
                crate::parser::ast::BinOp::Ge => ">=",
                crate::parser::ast::BinOp::And => "&&",
                crate::parser::ast::BinOp::Or => "||",
            };
            Ok(format!("{} {} {}", left_js, op_js, right_js))
        }

        IrExpr::If {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            let mut output = String::new();
            output.push_str(&indent_str);
            output.push_str("if (");
            output.push_str(&compile_expr(condition, 0)?);
            output.push_str(") {\n");

            let then_js = compile_expr(then_branch, indent + 1)?;
            output.push_str(&then_js);
            output.push('\n');

            output.push_str(&indent_str);
            output.push_str("} else {\n");

            let else_js = compile_expr(else_branch, indent + 1)?;
            output.push_str(&else_js);
            output.push('\n');

            output.push_str(&indent_str);
            output.push('}');

            Ok(output)
        }

        IrExpr::Match { expr, cases, .. } => {
            // Use the pattern compiler to generate advanced pattern matching
            compile_match_with_patterns(expr, cases, indent)
        }

        IrExpr::Let {
            name, value, body, ..
        } => {
            let mut output = String::new();
            output.push_str(&indent_str);
            output.push_str("const ");
            output.push_str(name);
            output.push_str(" = ");
            output.push_str(&compile_expr(value, 0)?);
            output.push_str(";\n");

            let body_js = compile_expr(body, indent)?;
            output.push_str(&body_js);

            Ok(output)
        }

        IrExpr::EffectCall(name, args, _) => {
            let args_js: Result<Vec<String>, _> = args.iter().map(|a| compile_expr(a, 0)).collect();
            let args_js = args_js?;
            Ok(format!("{}({})", name, args_js.join(", ")))
        }

        IrExpr::RespondJson(expr, _) => {
            let expr_js = compile_expr(expr, 0)?;
            Ok(format!("return JSON.stringifyCanonical({});", expr_js))
        }
    }
}
