//! JavaScript subset parser for MTPJS runtime
//!
//! This module implements a parser for the constrained JavaScript subset
//! generated by the MTPScript compiler. It parses JS text into JsExpr AST nodes.
//!
//! FORBIDDEN CONSTRUCTS (per spec §12):
//! - eval
//! - class
//! - this
//! - try/catch
//! - loops (for, while, do)
//! - new
//! - prototype
//! - arguments
//! - global mutation

use crate::errors::runtime::RuntimeError;
use crate::runtime::interpreter::JsExpr;
use crate::runtime::value::Value;

/// Token types for the JS subset lexer
#[derive(Debug, Clone, PartialEq)]
pub enum JsToken {
    // Keywords
    Function,
    Return,
    Const,
    If,
    Else,
    True,
    False,
    Null,

    // Identifiers and literals
    Ident(String),
    Number(i64),
    Float(f64),
    String(String),

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    EqEq,
    EqEqEq,
    BangEq,
    BangEqEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    AmpAmp,
    PipePipe,
    Bang,
    Eq,

    // Delimiters
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Colon,
    Semicolon,
    Dot,

    // Special
    Eof,
}

/// Lexer for JS subset
pub struct JsLexer<'a> {
    source: &'a str,
    chars: std::iter::Peekable<std::str::CharIndices<'a>>,
    current_pos: usize,
}

impl<'a> JsLexer<'a> {
    pub fn new(source: &'a str) -> Self {
        Self {
            source,
            chars: source.char_indices().peekable(),
            current_pos: 0,
        }
    }

    fn advance(&mut self) -> Option<char> {
        if let Some((pos, c)) = self.chars.next() {
            self.current_pos = pos;
            Some(c)
        } else {
            None
        }
    }

    fn peek(&mut self) -> Option<char> {
        self.chars.peek().map(|(_, c)| *c)
    }

    fn peek_next(&self) -> Option<char> {
        let mut chars = self.chars.clone();
        chars.next();
        chars.peek().map(|(_, c)| *c)
    }

    fn skip_whitespace_and_comments(&mut self) {
        loop {
            match self.peek() {
                Some(c) if c.is_whitespace() => {
                    self.advance();
                }
                Some('/') => {
                    if self.peek_next() == Some('/') {
                        // Line comment
                        self.advance(); // consume first /
                        self.advance(); // consume second /
                        while let Some(c) = self.peek() {
                            if c == '\n' {
                                break;
                            }
                            self.advance();
                        }
                    } else if self.peek_next() == Some('*') {
                        // Block comment
                        self.advance(); // consume /
                        self.advance(); // consume *
                        while let Some(c) = self.peek() {
                            if c == '*' && self.peek_next() == Some('/') {
                                self.advance(); // consume *
                                self.advance(); // consume /
                                break;
                            }
                            self.advance();
                        }
                    } else {
                        break;
                    }
                }
                _ => break,
            }
        }
    }

    fn scan_number(&mut self, first_char: char) -> Result<JsToken, RuntimeError> {
        let mut num_str = first_char.to_string();
        let mut is_float = false;

        while let Some(c) = self.peek() {
            if c.is_ascii_digit() {
                num_str.push(c);
                self.advance();
            } else if c == '.' && !is_float {
                // Check if next char is a digit (not a method call)
                if let Some(next) = self.peek_next() {
                    if next.is_ascii_digit() {
                        is_float = true;
                        num_str.push(c);
                        self.advance();
                    } else {
                        break;
                    }
                } else {
                    break;
                }
            } else {
                break;
            }
        }

        if is_float {
            num_str
                .parse::<f64>()
                .map(JsToken::Float)
                .map_err(|_| RuntimeError::ValueError(format!("Invalid float: {}", num_str)))
        } else {
            num_str
                .parse::<i64>()
                .map(JsToken::Number)
                .map_err(|_| RuntimeError::ValueError(format!("Invalid number: {}", num_str)))
        }
    }

    fn scan_string(&mut self, quote: char) -> Result<JsToken, RuntimeError> {
        let mut s = String::new();
        let mut escaped = false;

        loop {
            match self.advance() {
                Some(c) if escaped => {
                    match c {
                        'n' => s.push('\n'),
                        't' => s.push('\t'),
                        'r' => s.push('\r'),
                        '\\' => s.push('\\'),
                        '"' => s.push('"'),
                        '\'' => s.push('\''),
                        _ => {
                            s.push('\\');
                            s.push(c);
                        }
                    }
                    escaped = false;
                }
                Some('\\') => {
                    escaped = true;
                }
                Some(c) if c == quote => {
                    return Ok(JsToken::String(s));
                }
                Some(c) => {
                    s.push(c);
                }
                None => {
                    return Err(RuntimeError::ValueError("Unterminated string".to_string()));
                }
            }
        }
    }

    fn scan_identifier(&mut self, first_char: char) -> JsToken {
        let mut ident = first_char.to_string();

        while let Some(c) = self.peek() {
            if c.is_alphanumeric() || c == '_' || c == '$' {
                ident.push(c);
                self.advance();
            } else {
                break;
            }
        }

        // Check for keywords
        match ident.as_str() {
            "function" => JsToken::Function,
            "return" => JsToken::Return,
            "const" => JsToken::Const,
            "if" => JsToken::If,
            "else" => JsToken::Else,
            "true" => JsToken::True,
            "false" => JsToken::False,
            "null" => JsToken::Null,
            // Forbidden constructs - will be caught at parse time
            _ => JsToken::Ident(ident),
        }
    }

    pub fn next_token(&mut self) -> Result<JsToken, RuntimeError> {
        self.skip_whitespace_and_comments();

        let c = match self.advance() {
            Some(c) => c,
            None => return Ok(JsToken::Eof),
        };

        match c {
            '(' => Ok(JsToken::LParen),
            ')' => Ok(JsToken::RParen),
            '{' => Ok(JsToken::LBrace),
            '}' => Ok(JsToken::RBrace),
            '[' => Ok(JsToken::LBracket),
            ']' => Ok(JsToken::RBracket),
            ',' => Ok(JsToken::Comma),
            ':' => Ok(JsToken::Colon),
            ';' => Ok(JsToken::Semicolon),
            '.' => Ok(JsToken::Dot),
            '+' => Ok(JsToken::Plus),
            '-' => Ok(JsToken::Minus),
            '*' => Ok(JsToken::Star),
            '/' => Ok(JsToken::Slash),
            '%' => Ok(JsToken::Percent),
            '=' => {
                if self.peek() == Some('=') {
                    self.advance();
                    if self.peek() == Some('=') {
                        self.advance();
                        Ok(JsToken::EqEqEq)
                    } else {
                        Ok(JsToken::EqEq)
                    }
                } else {
                    Ok(JsToken::Eq)
                }
            }
            '!' => {
                if self.peek() == Some('=') {
                    self.advance();
                    if self.peek() == Some('=') {
                        self.advance();
                        Ok(JsToken::BangEqEq)
                    } else {
                        Ok(JsToken::BangEq)
                    }
                } else {
                    Ok(JsToken::Bang)
                }
            }
            '<' => {
                if self.peek() == Some('=') {
                    self.advance();
                    Ok(JsToken::LtEq)
                } else {
                    Ok(JsToken::Lt)
                }
            }
            '>' => {
                if self.peek() == Some('=') {
                    self.advance();
                    Ok(JsToken::GtEq)
                } else {
                    Ok(JsToken::Gt)
                }
            }
            '&' => {
                if self.peek() == Some('&') {
                    self.advance();
                    Ok(JsToken::AmpAmp)
                } else {
                    Err(RuntimeError::ValueError(
                        "Unexpected character: &".to_string(),
                    ))
                }
            }
            '|' => {
                if self.peek() == Some('|') {
                    self.advance();
                    Ok(JsToken::PipePipe)
                } else {
                    Err(RuntimeError::ValueError(
                        "Unexpected character: |".to_string(),
                    ))
                }
            }
            '"' | '\'' => self.scan_string(c),
            c if c.is_ascii_digit() => self.scan_number(c),
            c if c.is_alphabetic() || c == '_' || c == '$' => Ok(self.scan_identifier(c)),
            _ => Err(RuntimeError::ValueError(format!(
                "Unexpected character: {}",
                c
            ))),
        }
    }

    pub fn tokenize(&mut self) -> Result<Vec<JsToken>, RuntimeError> {
        let mut tokens = Vec::new();
        loop {
            let token = self.next_token()?;
            if token == JsToken::Eof {
                tokens.push(token);
                break;
            }
            tokens.push(token);
        }
        Ok(tokens)
    }
}

/// Parser for JS subset
pub struct JsParser {
    tokens: Vec<JsToken>,
    pos: usize,
}

impl JsParser {
    pub fn new(tokens: Vec<JsToken>) -> Self {
        Self { tokens, pos: 0 }
    }

    fn current(&self) -> &JsToken {
        self.tokens.get(self.pos).unwrap_or(&JsToken::Eof)
    }

    fn advance(&mut self) -> &JsToken {
        let token = self.current().clone();
        if self.pos < self.tokens.len() {
            self.pos += 1;
        }
        self.tokens.get(self.pos - 1).unwrap_or(&JsToken::Eof)
    }

    fn peek(&self) -> &JsToken {
        self.tokens.get(self.pos).unwrap_or(&JsToken::Eof)
    }

    fn peek_next(&self) -> &JsToken {
        self.tokens.get(self.pos + 1).unwrap_or(&JsToken::Eof)
    }

    fn expect(&mut self, expected: JsToken) -> Result<(), RuntimeError> {
        let current = self.current().clone();
        if std::mem::discriminant(&current) == std::mem::discriminant(&expected) {
            self.advance();
            Ok(())
        } else {
            Err(RuntimeError::ValueError(format!(
                "Expected {:?}, got {:?}",
                expected, current
            )))
        }
    }

    fn check(&self, token: &JsToken) -> bool {
        std::mem::discriminant(self.current()) == std::mem::discriminant(token)
    }

    fn match_token(&mut self, token: &JsToken) -> bool {
        if self.check(token) {
            self.advance();
            true
        } else {
            false
        }
    }

    /// Parse a complete JS program
    pub fn parse_program(&mut self) -> Result<JsExpr, RuntimeError> {
        // First check for forbidden constructs
        self.check_forbidden_constructs()?;

        let mut statements = Vec::new();

        while !self.check(&JsToken::Eof) {
            let stmt = self.parse_statement()?;
            statements.push(stmt);
        }

        Ok(JsExpr::Program(statements))
    }

    fn check_forbidden_constructs(&self) -> Result<(), RuntimeError> {
        let forbidden = [
            "class",
            "this",
            "eval",
            "try",
            "catch",
            "new",
            "prototype",
            "arguments",
            "for",
            "while",
            "do",
            "switch",
            "var",
            "let",
            "throw",
            "async",
            "await",
            "yield",
            "import",
            "export",
            "with",
            "delete",
            "typeof",
            "instanceof",
            "in",
        ];

        for token in &self.tokens {
            if let JsToken::Ident(name) = token {
                if forbidden.contains(&name.as_str()) {
                    return Err(RuntimeError::ValueError(format!(
                        "Forbidden JS construct: {}",
                        name
                    )));
                }
            }
        }

        Ok(())
    }

    fn parse_statement(&mut self) -> Result<JsExpr, RuntimeError> {
        match self.current() {
            JsToken::Function => self.parse_function_decl(),
            JsToken::Const => self.parse_const_decl(),
            JsToken::Return => self.parse_return_stmt(),
            JsToken::If => self.parse_if_stmt(),
            _ => {
                let expr = self.parse_expression()?;
                // Consume optional semicolon
                self.match_token(&JsToken::Semicolon);
                Ok(JsExpr::ExprStmt(Box::new(expr)))
            }
        }
    }

    fn parse_function_decl(&mut self) -> Result<JsExpr, RuntimeError> {
        self.expect(JsToken::Function)?;

        // Function name
        let name = match self.current().clone() {
            JsToken::Ident(name) => {
                self.advance();
                name
            }
            _ => {
                return Err(RuntimeError::ValueError(
                    "Expected function name".to_string(),
                ))
            }
        };

        // Parameters
        self.expect(JsToken::LParen)?;
        let params = self.parse_param_list()?;
        self.expect(JsToken::RParen)?;

        // Body
        self.expect(JsToken::LBrace)?;
        let body = self.parse_block_contents()?;
        self.expect(JsToken::RBrace)?;

        Ok(JsExpr::FunctionDecl {
            name,
            params,
            body: Box::new(body),
        })
    }

    fn parse_param_list(&mut self) -> Result<Vec<String>, RuntimeError> {
        let mut params = Vec::new();

        if self.check(&JsToken::RParen) {
            return Ok(params);
        }

        loop {
            match self.current().clone() {
                JsToken::Ident(name) => {
                    self.advance();
                    params.push(name);
                }
                _ => {
                    return Err(RuntimeError::ValueError(
                        "Expected parameter name".to_string(),
                    ))
                }
            }

            if !self.match_token(&JsToken::Comma) {
                break;
            }
        }

        Ok(params)
    }

    fn parse_block_contents(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut statements = Vec::new();

        while !self.check(&JsToken::RBrace) && !self.check(&JsToken::Eof) {
            let stmt = self.parse_statement()?;
            statements.push(stmt);
        }

        if statements.is_empty() {
            Ok(JsExpr::Literal(Value::Null))
        } else if statements.len() == 1 {
            Ok(statements.pop().unwrap())
        } else {
            Ok(JsExpr::Block(statements))
        }
    }

    fn parse_const_decl(&mut self) -> Result<JsExpr, RuntimeError> {
        self.expect(JsToken::Const)?;

        let name = match self.current().clone() {
            JsToken::Ident(name) => {
                self.advance();
                name
            }
            _ => {
                return Err(RuntimeError::ValueError(
                    "Expected variable name".to_string(),
                ))
            }
        };

        self.expect(JsToken::Eq)?;
        let value = self.parse_expression()?;
        self.match_token(&JsToken::Semicolon);

        Ok(JsExpr::Const {
            name,
            value: Box::new(value),
        })
    }

    fn parse_return_stmt(&mut self) -> Result<JsExpr, RuntimeError> {
        self.expect(JsToken::Return)?;

        // Check for empty return or return followed by semicolon/closing brace
        if self.check(&JsToken::Semicolon)
            || self.check(&JsToken::RBrace)
            || self.check(&JsToken::Eof)
        {
            self.match_token(&JsToken::Semicolon);
            return Ok(JsExpr::Return(None));
        }

        let value = self.parse_expression()?;
        self.match_token(&JsToken::Semicolon);

        Ok(JsExpr::Return(Some(Box::new(value))))
    }

    fn parse_if_stmt(&mut self) -> Result<JsExpr, RuntimeError> {
        self.expect(JsToken::If)?;
        self.expect(JsToken::LParen)?;
        let condition = self.parse_expression()?;
        self.expect(JsToken::RParen)?;

        self.expect(JsToken::LBrace)?;
        let then_branch = self.parse_block_contents()?;
        self.expect(JsToken::RBrace)?;

        let else_branch = if self.match_token(&JsToken::Else) {
            self.expect(JsToken::LBrace)?;
            let else_block = self.parse_block_contents()?;
            self.expect(JsToken::RBrace)?;
            Some(Box::new(else_block))
        } else {
            None
        };

        Ok(JsExpr::If(
            Box::new(condition),
            Box::new(then_branch),
            else_branch,
        ))
    }

    fn parse_expression(&mut self) -> Result<JsExpr, RuntimeError> {
        self.parse_or_expr()
    }

    fn parse_or_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_and_expr()?;

        while self.check(&JsToken::PipePipe) {
            self.advance();
            let right = self.parse_and_expr()?;
            left = JsExpr::BinOp("||".to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_and_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_equality_expr()?;

        while self.check(&JsToken::AmpAmp) {
            self.advance();
            let right = self.parse_equality_expr()?;
            left = JsExpr::BinOp("&&".to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_equality_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_comparison_expr()?;

        loop {
            let op = match self.current() {
                JsToken::EqEq => "==",
                JsToken::EqEqEq => "===",
                JsToken::BangEq => "!=",
                JsToken::BangEqEq => "!==",
                _ => break,
            };
            self.advance();
            let right = self.parse_comparison_expr()?;
            left = JsExpr::BinOp(op.to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_comparison_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_additive_expr()?;

        loop {
            let op = match self.current() {
                JsToken::Lt => "<",
                JsToken::Gt => ">",
                JsToken::LtEq => "<=",
                JsToken::GtEq => ">=",
                _ => break,
            };
            self.advance();
            let right = self.parse_additive_expr()?;
            left = JsExpr::BinOp(op.to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_additive_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_multiplicative_expr()?;

        loop {
            let op = match self.current() {
                JsToken::Plus => "+",
                JsToken::Minus => "-",
                _ => break,
            };
            self.advance();
            let right = self.parse_multiplicative_expr()?;
            left = JsExpr::BinOp(op.to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_multiplicative_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut left = self.parse_unary_expr()?;

        loop {
            let op = match self.current() {
                JsToken::Star => "*",
                JsToken::Slash => "/",
                JsToken::Percent => "%",
                _ => break,
            };
            self.advance();
            let right = self.parse_unary_expr()?;
            left = JsExpr::BinOp(op.to_string(), Box::new(left), Box::new(right));
        }

        Ok(left)
    }

    fn parse_unary_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        match self.current() {
            JsToken::Bang => {
                self.advance();
                let expr = self.parse_unary_expr()?;
                Ok(JsExpr::UnaryOp("!".to_string(), Box::new(expr)))
            }
            JsToken::Minus => {
                self.advance();
                let expr = self.parse_unary_expr()?;
                Ok(JsExpr::UnaryOp("-".to_string(), Box::new(expr)))
            }
            _ => self.parse_call_expr(),
        }
    }

    fn parse_call_expr(&mut self) -> Result<JsExpr, RuntimeError> {
        let mut expr = self.parse_primary()?;

        loop {
            match self.current() {
                JsToken::LParen => {
                    self.advance();
                    let args = self.parse_arg_list()?;
                    self.expect(JsToken::RParen)?;
                    expr = JsExpr::Call(Box::new(expr), args);
                }
                JsToken::Dot => {
                    self.advance();
                    match self.current().clone() {
                        JsToken::Ident(name) => {
                            self.advance();
                            expr = JsExpr::Member(Box::new(expr), name);
                        }
                        _ => {
                            return Err(RuntimeError::ValueError(
                                "Expected property name after dot".to_string(),
                            ))
                        }
                    }
                }
                JsToken::LBracket => {
                    self.advance();
                    let index = self.parse_expression()?;
                    self.expect(JsToken::RBracket)?;
                    expr = JsExpr::Index(Box::new(expr), Box::new(index));
                }
                _ => break,
            }
        }

        Ok(expr)
    }

    fn parse_arg_list(&mut self) -> Result<Vec<JsExpr>, RuntimeError> {
        let mut args = Vec::new();

        if self.check(&JsToken::RParen) {
            return Ok(args);
        }

        loop {
            args.push(self.parse_expression()?);
            if !self.match_token(&JsToken::Comma) {
                break;
            }
        }

        Ok(args)
    }

    fn parse_primary(&mut self) -> Result<JsExpr, RuntimeError> {
        let current = self.current().clone();

        match current {
            JsToken::Number(n) => {
                self.advance();
                Ok(JsExpr::Literal(Value::Number(n)))
            }
            JsToken::Float(f) => {
                self.advance();
                // Convert float to string for Decimal-like handling
                // MTPScript doesn't use floats, so this is for compatibility
                // In strict mode, we'd reject floats
                Ok(JsExpr::Literal(Value::Number(f as i64)))
            }
            JsToken::String(s) => {
                self.advance();
                Ok(JsExpr::Literal(Value::String(s)))
            }
            JsToken::True => {
                self.advance();
                Ok(JsExpr::Literal(Value::Boolean(true)))
            }
            JsToken::False => {
                self.advance();
                Ok(JsExpr::Literal(Value::Boolean(false)))
            }
            JsToken::Null => {
                self.advance();
                Ok(JsExpr::Literal(Value::Null))
            }
            JsToken::Ident(name) => {
                self.advance();
                Ok(JsExpr::Ident(name))
            }
            JsToken::LParen => {
                self.advance();
                let expr = self.parse_expression()?;
                self.expect(JsToken::RParen)?;
                Ok(expr)
            }
            JsToken::LBracket => {
                self.advance();
                let elements = self.parse_array_elements()?;
                self.expect(JsToken::RBracket)?;
                Ok(JsExpr::Array(elements))
            }
            JsToken::LBrace => {
                self.advance();
                let fields = self.parse_object_fields()?;
                self.expect(JsToken::RBrace)?;
                Ok(JsExpr::Object(fields))
            }
            _ => Err(RuntimeError::ValueError(format!(
                "Unexpected token: {:?}",
                current
            ))),
        }
    }

    fn parse_array_elements(&mut self) -> Result<Vec<JsExpr>, RuntimeError> {
        let mut elements = Vec::new();

        if self.check(&JsToken::RBracket) {
            return Ok(elements);
        }

        loop {
            elements.push(self.parse_expression()?);
            if !self.match_token(&JsToken::Comma) {
                break;
            }
        }

        Ok(elements)
    }

    fn parse_object_fields(&mut self) -> Result<Vec<(String, JsExpr)>, RuntimeError> {
        let mut fields = Vec::new();

        if self.check(&JsToken::RBrace) {
            return Ok(fields);
        }

        loop {
            // Key can be string or identifier
            let key = match self.current().clone() {
                JsToken::String(s) => {
                    self.advance();
                    s
                }
                JsToken::Ident(s) => {
                    self.advance();
                    s
                }
                _ => return Err(RuntimeError::ValueError("Expected object key".to_string())),
            };

            self.expect(JsToken::Colon)?;
            let value = self.parse_expression()?;
            fields.push((key, value));

            if !self.match_token(&JsToken::Comma) {
                break;
            }
        }

        Ok(fields)
    }
}

/// Parse a JS program string into JsExpr AST
pub fn parse_js_program(source: &str) -> Result<JsExpr, RuntimeError> {
    let mut lexer = JsLexer::new(source);
    let tokens = lexer.tokenize()?;
    let mut parser = JsParser::new(tokens);
    parser.parse_program()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tokenize_simple() {
        let mut lexer = JsLexer::new("function add(a, b) { return a + b; }");
        let tokens = lexer.tokenize().unwrap();
        assert!(tokens.contains(&JsToken::Function));
        assert!(tokens.contains(&JsToken::Return));
    }

    #[test]
    fn test_tokenize_numbers() {
        let mut lexer = JsLexer::new("42 3.14 0");
        let tokens = lexer.tokenize().unwrap();
        assert!(matches!(tokens[0], JsToken::Number(42)));
        assert!(matches!(tokens[1], JsToken::Float(_)));
        assert!(matches!(tokens[2], JsToken::Number(0)));
    }

    #[test]
    fn test_tokenize_strings() {
        let mut lexer = JsLexer::new(r#""hello" 'world'"#);
        let tokens = lexer.tokenize().unwrap();
        assert!(matches!(&tokens[0], JsToken::String(s) if s == "hello"));
        assert!(matches!(&tokens[1], JsToken::String(s) if s == "world"));
    }

    #[test]
    fn test_tokenize_operators() {
        let mut lexer = JsLexer::new("+ - * / === !== == != < > <= >= && ||");
        let tokens = lexer.tokenize().unwrap();
        assert!(tokens.contains(&JsToken::Plus));
        assert!(tokens.contains(&JsToken::EqEqEq));
        assert!(tokens.contains(&JsToken::BangEqEq));
        assert!(tokens.contains(&JsToken::AmpAmp));
        assert!(tokens.contains(&JsToken::PipePipe));
    }

    #[test]
    fn test_parse_simple_function() {
        let ast = parse_js_program("function add(a, b) { return a + b; }").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::FunctionDecl { name, params, .. } => {
                        assert_eq!(name, "add");
                        assert_eq!(params, &["a", "b"]);
                    }
                    _ => panic!("Expected FunctionDecl"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_const_decl() {
        let ast = parse_js_program("const x = 42;").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::Const { name, value } => {
                        assert_eq!(name, "x");
                        assert!(matches!(value.as_ref(), JsExpr::Literal(Value::Number(42))));
                    }
                    _ => panic!("Expected Const"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_function_call() {
        let ast = parse_js_program("add(1, 2);").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::ExprStmt(expr) => match expr.as_ref() {
                        JsExpr::Call(func, args) => {
                            assert!(matches!(func.as_ref(), JsExpr::Ident(n) if n == "add"));
                            assert_eq!(args.len(), 2);
                        }
                        _ => panic!("Expected Call"),
                    },
                    _ => panic!("Expected ExprStmt"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_if_else() {
        let ast = parse_js_program("if (x > 0) { return 1; } else { return 0; }").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                assert!(matches!(&stmts[0], JsExpr::If(_, _, Some(_))));
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_object_literal() {
        let ast = parse_js_program(r#"{"key": "value", "num": 42}"#).unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::ExprStmt(expr) => match expr.as_ref() {
                        JsExpr::Object(fields) => {
                            assert_eq!(fields.len(), 2);
                        }
                        _ => panic!("Expected Object"),
                    },
                    _ => panic!("Expected ExprStmt"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_array_literal() {
        let ast = parse_js_program("[1, 2, 3]").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::ExprStmt(expr) => match expr.as_ref() {
                        JsExpr::Array(elements) => {
                            assert_eq!(elements.len(), 3);
                        }
                        _ => panic!("Expected Array"),
                    },
                    _ => panic!("Expected ExprStmt"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_member_access() {
        let ast = parse_js_program("obj.prop.sub").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                match &stmts[0] {
                    JsExpr::ExprStmt(expr) => match expr.as_ref() {
                        JsExpr::Member(inner, prop) => {
                            assert_eq!(prop, "sub");
                            assert!(matches!(
                                inner.as_ref(),
                                JsExpr::Member(_, p) if p == "prop"
                            ));
                        }
                        _ => panic!("Expected Member"),
                    },
                    _ => panic!("Expected ExprStmt"),
                }
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_forbidden_construct_class() {
        let result = parse_js_program("class Foo {}");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_construct_this() {
        let result = parse_js_program("function f() { return this; }");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_construct_eval() {
        let result = parse_js_program("eval('code')");
        assert!(result.is_err());
    }

    #[test]
    fn test_comments_ignored() {
        let ast = parse_js_program(
            r#"
            // This is a comment
            function add(a, b) {
                /* Multi-line
                   comment */
                return a + b;
            }
        "#,
        )
        .unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
            }
            _ => panic!("Expected Program"),
        }
    }

    #[test]
    fn test_parse_complex_expression() {
        let ast = parse_js_program("1 + 2 * 3 - 4 / 2").unwrap();
        match ast {
            JsExpr::Program(stmts) => {
                assert_eq!(stmts.len(), 1);
                // Just verify it parses without error
            }
            _ => panic!("Expected Program"),
        }
    }
}
