//! Integration tests for JS subset execution
//!
//! These tests verify that the interpreter can:
//! 1. Parse JS code generated by the MTPScript compiler
//! 2. Execute functions correctly
//! 3. Handle all supported JS constructs
//! 4. Reject forbidden constructs
//! 5. Produce deterministic results

use mtpscript_core::runtime::interpreter::Interpreter;
use mtpscript_core::runtime::value::Value;

#[cfg(test)]
mod tests {
    use super::*;

    // ============================================================
    // Basic Execution Tests
    // ============================================================

    #[test]
    fn test_execute_simple_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("42;").unwrap();
        assert_eq!(result, Value::Number(42));
    }

    #[test]
    fn test_execute_string_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute(r#""hello";"#).unwrap();
        assert_eq!(result, Value::String("hello".to_string()));
    }

    #[test]
    fn test_execute_boolean_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("true;").unwrap();
        assert_eq!(result, Value::Boolean(true));

        let result = interp.execute("false;").unwrap();
        assert_eq!(result, Value::Boolean(false));
    }

    #[test]
    fn test_execute_null_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("null;").unwrap();
        assert_eq!(result, Value::Null);
    }

    // ============================================================
    // Arithmetic Operations
    // ============================================================

    #[test]
    fn test_execute_addition() {
        let mut interp = Interpreter::new();
        let result = interp.execute("1 + 2;").unwrap();
        assert_eq!(result, Value::Number(3));
    }

    #[test]
    fn test_execute_subtraction() {
        let mut interp = Interpreter::new();
        let result = interp.execute("10 - 3;").unwrap();
        assert_eq!(result, Value::Number(7));
    }

    #[test]
    fn test_execute_multiplication() {
        let mut interp = Interpreter::new();
        let result = interp.execute("4 * 5;").unwrap();
        assert_eq!(result, Value::Number(20));
    }

    #[test]
    fn test_execute_division() {
        let mut interp = Interpreter::new();
        let result = interp.execute("15 / 3;").unwrap();
        assert_eq!(result, Value::Number(5));
    }

    #[test]
    fn test_execute_complex_arithmetic() {
        let mut interp = Interpreter::new();
        // Precedence test: 2 + 3 * 4 = 2 + 12 = 14
        let result = interp.execute("2 + 3 * 4;").unwrap();
        assert_eq!(result, Value::Number(14));
    }

    #[test]
    fn test_execute_parentheses_grouping() {
        let mut interp = Interpreter::new();
        // (2 + 3) * 4 = 5 * 4 = 20
        let result = interp.execute("(2 + 3) * 4;").unwrap();
        assert_eq!(result, Value::Number(20));
    }

    // ============================================================
    // Comparison Operations
    // ============================================================

    #[test]
    fn test_execute_equality() {
        let mut interp = Interpreter::new();
        let result = interp.execute("5 === 5;").unwrap();
        assert_eq!(result, Value::Boolean(true));

        let result = interp.execute("5 === 6;").unwrap();
        assert_eq!(result, Value::Boolean(false));
    }

    #[test]
    fn test_execute_inequality() {
        let mut interp = Interpreter::new();
        let result = interp.execute("5 !== 6;").unwrap();
        assert_eq!(result, Value::Boolean(true));
    }

    #[test]
    fn test_execute_less_than() {
        let mut interp = Interpreter::new();
        let result = interp.execute("3 < 5;").unwrap();
        assert_eq!(result, Value::Boolean(true));

        let result = interp.execute("5 < 3;").unwrap();
        assert_eq!(result, Value::Boolean(false));
    }

    #[test]
    fn test_execute_greater_than() {
        let mut interp = Interpreter::new();
        let result = interp.execute("5 > 3;").unwrap();
        assert_eq!(result, Value::Boolean(true));
    }

    #[test]
    fn test_execute_less_than_or_equal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("5 <= 5;").unwrap();
        assert_eq!(result, Value::Boolean(true));
    }

    #[test]
    fn test_execute_greater_than_or_equal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("5 >= 5;").unwrap();
        assert_eq!(result, Value::Boolean(true));
    }

    // ============================================================
    // Logical Operations
    // ============================================================

    #[test]
    fn test_execute_logical_and() {
        let mut interp = Interpreter::new();
        let result = interp.execute("true && true;").unwrap();
        assert_eq!(result, Value::Boolean(true));

        let result = interp.execute("true && false;").unwrap();
        assert_eq!(result, Value::Boolean(false));
    }

    #[test]
    fn test_execute_logical_or() {
        let mut interp = Interpreter::new();
        let result = interp.execute("true || false;").unwrap();
        assert_eq!(result, Value::Boolean(true));

        let result = interp.execute("false || false;").unwrap();
        assert_eq!(result, Value::Boolean(false));
    }

    #[test]
    fn test_execute_logical_not() {
        let mut interp = Interpreter::new();
        let result = interp.execute("!true;").unwrap();
        assert_eq!(result, Value::Boolean(false));

        let result = interp.execute("!false;").unwrap();
        assert_eq!(result, Value::Boolean(true));
    }

    // ============================================================
    // Array Operations
    // ============================================================

    #[test]
    fn test_execute_array_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute("[1, 2, 3];").unwrap();
        match result {
            Value::Array(arr) => {
                assert_eq!(arr.len(), 3);
                assert_eq!(arr[0], Value::Number(1));
                assert_eq!(arr[1], Value::Number(2));
                assert_eq!(arr[2], Value::Number(3));
            }
            _ => panic!("Expected array, got {:?}", result),
        }
    }

    #[test]
    fn test_execute_empty_array() {
        let mut interp = Interpreter::new();
        let result = interp.execute("[];").unwrap();
        match result {
            Value::Array(arr) => {
                assert_eq!(arr.len(), 0);
            }
            _ => panic!("Expected empty array"),
        }
    }

    // ============================================================
    // Object Operations
    // ============================================================

    #[test]
    fn test_execute_object_literal() {
        let mut interp = Interpreter::new();
        let result = interp.execute(r#"{"a": 1, "b": 2};"#).unwrap();
        match result {
            Value::Object(obj) => {
                assert_eq!(obj.get("a"), Some(&Value::Number(1)));
                assert_eq!(obj.get("b"), Some(&Value::Number(2)));
            }
            _ => panic!("Expected object"),
        }
    }

    #[test]
    fn test_execute_empty_object() {
        let mut interp = Interpreter::new();
        let result = interp.execute("{};").unwrap();
        match result {
            Value::Object(obj) => {
                assert_eq!(obj.len(), 0);
            }
            _ => panic!("Expected empty object"),
        }
    }

    // ============================================================
    // Function Declarations and Calls
    // ============================================================

    #[test]
    fn test_execute_simple_function() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            function add(a, b) {
                return a + b;
            }
            add(3, 4);
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(7));
    }

    #[test]
    fn test_execute_function_with_return() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            function double(x) {
                return x * 2;
            }
            double(21);
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(42));
    }

    #[test]
    fn test_execute_multiple_functions() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            function add(a, b) { return a + b; }
            function mul(a, b) { return a * b; }
            mul(add(2, 3), 4);
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(20)); // (2+3) * 4 = 20
    }

    #[test]
    fn test_execute_nested_function_calls() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            function f(x) { return x + 1; }
            function g(x) { return x * 2; }
            f(g(f(g(1))));
        "#,
            )
            .unwrap();
        // g(1) = 2, f(2) = 3, g(3) = 6, f(6) = 7
        assert_eq!(result, Value::Number(7));
    }

    // ============================================================
    // Const Declarations
    // ============================================================

    #[test]
    fn test_execute_const_declaration() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const x = 42;
            x;
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(42));
    }

    #[test]
    fn test_execute_multiple_const_declarations() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const a = 10;
            const b = 20;
            const c = a + b;
            c;
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(30));
    }

    // ============================================================
    // If-Else Statements
    // ============================================================

    #[test]
    fn test_execute_if_true() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            if (true) {
                1;
            } else {
                2;
            }
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(1));
    }

    #[test]
    fn test_execute_if_false() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            if (false) {
                1;
            } else {
                2;
            }
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(2));
    }

    #[test]
    fn test_execute_if_with_expression() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const x = 10;
            if (x > 5) {
                return x * 2;
            } else {
                return x;
            }
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(20));
    }

    // ============================================================
    // String Operations
    // ============================================================

    #[test]
    fn test_execute_string_concatenation() {
        let mut interp = Interpreter::new();
        let result = interp.execute(r#""hello" + " " + "world";"#).unwrap();
        assert_eq!(result, Value::String("hello world".to_string()));
    }

    // ============================================================
    // Member Access
    // ============================================================

    #[test]
    fn test_execute_member_access() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const obj = {"x": 10, "y": 20};
            obj.x + obj.y;
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(30));
    }

    // ============================================================
    // Index Access
    // ============================================================

    #[test]
    fn test_execute_array_index() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const arr = [10, 20, 30];
            arr[1];
        "#,
            )
            .unwrap();
        assert_eq!(result, Value::Number(20));
    }

    // ============================================================
    // Built-in Functions
    // ============================================================

    #[test]
    fn test_execute_json_stringify() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const obj = {"name": "test"};
            JSON.stringifyCanonical(obj);
        "#,
            )
            .unwrap();
        match result {
            Value::String(s) => {
                assert!(s.contains("name"));
                assert!(s.contains("test"));
            }
            _ => panic!("Expected string from JSON.stringifyCanonical"),
        }
    }

    // ============================================================
    // Forbidden Constructs
    // ============================================================

    #[test]
    fn test_forbidden_class() {
        let mut interp = Interpreter::new();
        let result = interp.execute("class Foo {}");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_this() {
        let mut interp = Interpreter::new();
        let result = interp.execute("function f() { return this; }");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_eval() {
        let mut interp = Interpreter::new();
        let result = interp.execute(r#"eval("1+1")"#);
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_new() {
        let mut interp = Interpreter::new();
        let result = interp.execute("new Object()");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_for_loop() {
        let mut interp = Interpreter::new();
        let result = interp.execute("for (let i = 0; i < 10; i++) {}");
        assert!(result.is_err());
    }

    #[test]
    fn test_forbidden_while_loop() {
        let mut interp = Interpreter::new();
        let result = interp.execute("while (true) {}");
        assert!(result.is_err());
    }

    // ============================================================
    // Gas Metering
    // ============================================================

    #[test]
    fn test_gas_exhaustion() {
        let mut interp = Interpreter::new();
        interp.set_gas_limit(10); // Very low limit

        // This should exhaust gas
        let result = interp.execute(
            r#"
            function recursive(n) {
                if (n <= 0) { return 0; }
                else { return recursive(n - 1); }
            }
            recursive(100);
        "#,
        );

        assert!(result.is_err());
    }

    #[test]
    fn test_gas_tracking() {
        let mut interp = Interpreter::new();
        let initial_gas = interp.gas_used();

        let _ = interp.execute("1 + 2 + 3 + 4 + 5;");

        let final_gas = interp.gas_used();
        assert!(final_gas > initial_gas);
    }

    // ============================================================
    // Determinism Tests
    // ============================================================

    #[test]
    fn test_deterministic_execution() {
        let code = r#"
            function compute(x) {
                return x * 2 + 1;
            }
            compute(10) + compute(20);
        "#;

        let mut results = Vec::new();
        for _ in 0..10 {
            let mut interp = Interpreter::new();
            let result = interp.execute(code).unwrap();
            results.push(result);
        }

        // All results should be identical
        for result in &results {
            assert_eq!(result, &results[0]);
        }

        // Verify the value: compute(10) = 21, compute(20) = 41, sum = 62
        assert_eq!(results[0], Value::Number(62));
    }

    #[test]
    fn test_deterministic_json_output() {
        let code = r#"
            const result = {"b": 2, "a": 1};
            JSON.stringifyCanonical(result);
        "#;

        let mut interp = Interpreter::new();
        let result1 = interp.execute(code).unwrap();

        let mut interp2 = Interpreter::new();
        let result2 = interp2.execute(code).unwrap();

        assert_eq!(result1, result2);
    }

    // ============================================================
    // Complex Integration Tests
    // ============================================================

    #[test]
    fn test_simulated_api_handler() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            // Simulated generated code from MTPScript compiler
            function compute_result(x, y) {
                return x + y;
            }

            function handle_get__api(input) {
                const result = compute_result(input, 10);
                return JSON.stringifyCanonical({"result": result});
            }

            handle_get__api(5);
        "#,
            )
            .unwrap();

        match result {
            Value::String(s) => {
                assert!(s.contains("result"));
                assert!(s.contains("15")); // 5 + 10 = 15
            }
            _ => panic!("Expected JSON string result"),
        }
    }

    #[test]
    fn test_conditional_logic() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            function max(a, b) {
                if (a > b) {
                    return a;
                } else {
                    return b;
                }
            }

            function abs(x) {
                if (x < 0) {
                    return 0 - x;
                } else {
                    return x;
                }
            }

            max(abs(-10), abs(5));
        "#,
            )
            .unwrap();

        assert_eq!(result, Value::Number(10));
    }

    #[test]
    fn test_data_transformation() {
        let mut interp = Interpreter::new();
        let result = interp
            .execute(
                r#"
            const data = {"x": 1, "y": 2, "z": 3};
            const sum = data.x + data.y + data.z;
            {"total": sum, "count": 3};
        "#,
            )
            .unwrap();

        match result {
            Value::Object(obj) => {
                assert_eq!(obj.get("total"), Some(&Value::Number(6)));
                assert_eq!(obj.get("count"), Some(&Value::Number(3)));
            }
            _ => panic!("Expected object result"),
        }
    }

    // ============================================================
    // Error Handling Tests
    // ============================================================

    #[test]
    fn test_undefined_variable_error() {
        let mut interp = Interpreter::new();
        let result = interp.execute("undefined_var;");
        assert!(result.is_err());
    }

    #[test]
    fn test_undefined_function_error() {
        let mut interp = Interpreter::new();
        let result = interp.execute("undefined_function();");
        assert!(result.is_err());
    }

    #[test]
    fn test_type_error_addition() {
        let mut interp = Interpreter::new();
        let result = interp.execute("1 + true;");
        assert!(result.is_err());
    }

    #[test]
    fn test_division_by_zero() {
        let mut interp = Interpreter::new();
        let result = interp.execute("10 / 0;");
        assert!(result.is_err());
    }

    #[test]
    fn test_function_arity_error() {
        let mut interp = Interpreter::new();
        let result = interp.execute(
            r#"
            function add(a, b) { return a + b; }
            add(1);
        "#,
        );
        assert!(result.is_err());
    }
}
